### ISSUE TITLE
github status shows PR fails, although landscape.io shows a successful PR

### ISSUE THREAD

**Issue by nirizr** [landscapeio/landscape-issues#276]
For the past few days, all PRs under my [github repo](http://github.com/nirizr/rematch) are failed by landscape. For example, the folloing [PR ](https://github.com/nirizr/rematch/pull/211) shows as landscape failed it. When clicking the [details link](https://landscape.io/github/nirizr/rematch/pulls/211) I get an 500 server error blank page.

When checking the PR from "Pull requests" link in landscape's sidebar it shows a blue dash (instead of a green V or a red X).

When going to the overview page, the recent PR is shown under the "recent activity", when from there the details are viewable (and the PR is indeed successful).

While doing the following used to fix it in the past, it no longer helps (a new PR check is triggered, but it ends up with the same result).

    git commit --ammend
    git push -f

I will appreciate any help regarding this strange issue,
Thanks!

**Comment by carlio** [comment]
Hi @nirizr I think I may have tracked down this issue. There were a couple of problems at the same time: firstly the pypi cache Landscape uses had run out of disk space and secondly there was a bug where if the fork branch name changed in the PR over time, new checks for every push would use the old branch name and fail due to not finding the branch.

I have fixed both of those problems and I think that will mean that your PRs will start working again. I'm looking into the 500 error now but I suspect that is part of this same bug.

**Comment by carlio** [comment]
(Also the checkers sometimes run out of disk space which also causes failed checks... I'm working on making this all more stable)

**Comment by nirizr** [comment]
Thanks for the fast respone!

I've experienced sporadic 500s in the past, but this time it was consistent.
I didn't fully understand the branch name change issue (I don't think I changed branch names for PRs, but idk, maybe).

Update:
I made another run for the same PR, and the issue remained. I still the server error from github detail status line and from the list of pull requests in landscape. Status still failed while landscape shows a successful run.
Note: I tested it again with the same PR.

Thanks again!

**Comment by carlio** [comment]
Ok I have now tracked this down a bit more. It was a combination of 1) the check failing for the base revision into which the PR would be merged and 2) the PR status getting stuck in this situation and never updating the PR status correctly. Your PR [@nirizr/rematch #211](https://github.com/nirizr/rematch/pull/211) is [now working on Landscape](https://landscape.io/github/nirizr/rematch/pulls/211) and (hopefully) all new PRs should be ok after the earlier fixes to failing PRs. 

I'm going to go through the history of the last few weeks and start re-running some failed checks because I think this has affected a lot of PRs on lots of repositories...

**Comment by nirizr** [comment]
Yes, I can confirm issue is resolved.
I also triggered tests on another PR and landscape returned successful.

Thanks a lot!
Closing.

**Comment by skudriashev** [comment]
@carlio still doesn't work https://landscape.io/github/apache/incubator-airflow/pulls/2511
